import { ReactNode } from 'react';
import '@/app/css/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header>123</header>
        <main>{children}</main>
        <footer>123</footer>
      </body>
    </html>
  );
}
